### ISSUE TITLE
`#-` and `#|` causes flake8 warning and is usually formatted away

### ISSUE THREAD

**Issue by dtasev** [williamjameshandley/py2nb#2]
Very nice script for generating a notebook!

I seem to have encountered an issue with the `#-` and `#|` syntax when using `flake8` and `yapf`, as `flake8` gives a `E265` (as there's no space after the `#`) and `yapf` will always format it to have a space - thus breaking all code sections/markdown.

An easy fix would be to just accept `# -` and `# |`, a more complicated fix can use a config file to set the expected characters. 

What is your opinion on this? I'm happy to open a PR for either approach

**Comment by williamjameshandley** [comment]
Hi @dtasev. Glad to hear that you're finding it useful. I use it whenever students/collaborators need/provide `.ipynb` files. If you're a vim user, you might want to look into [vimteractive](https://github.com/williamjameshandley/vimteractive), which allows you to have the interactivity of `IPython` whilst working with text-based scripts.

 I think accepting `# -` and `# |` as additional special characters is a great solution. You'll need to make sure that it also works with the original `#-` and `#|`, otherwise it will be a breaking change. Submit a PR, and we can discuss further there.

**Comment by dtasev** [comment]
Closed with #3
